### ISSUE TITLE
TypoScript format is not kept

### ISSUE THREAD

**Issue by simonschaufi** [andreaswolf/fractor#197]
I have a file called `typoscript-lint.yml` in my root directory with the following content:

```yaml
paths:
  - packages/my_extension/Configuration/TypoScript
filePatterns:
  - "*.typoscript"
sniffs:
  - class: Indentation
    parameters:
      useSpaces: false
      indentPerLevel: 1
      indentConditions: true
```
and when running Fractor, the indentation is not kept as is. The whole file gets changed. Right now it can be configured for XML but is it also possible to configure it for TypoScript? I like to use tabs for TypoScript files
