### ISSUE TITLE
Fatal error in EmailFinisherYamlFractor.php

### ISSUE THREAD

**Issue by RKlingler** [andreaswolf/fractor#263]
Fractor throws the following error when I run it:
```
Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, string given in /var/www/html/vendor/a9f/typo3-fractor/rules/TYPO3v10/Yaml/EmailFinisherYamlFractor.php:137
```

The issue is caused by a form template, that I provide for editors. It comes preconfigured with an EmailToReceiver finisher, whose default settings are deliberately invalid, so that newly created forms don't get saved with missing configuration.

The template form definition looks something like this:
````
identifier: template
label: 'Template'
type: Form
finishers:
  -
    options:
      subject: ''
      recipients:
        '':''
      senderAddress: ''
      senderName: 'SENDERNAME'
    identifier: EmailToReceiver
````

For now I adjusted my configuration to simply skip the 'EmailFinisherYamlFractor'', which is fine, because I don't need it anyway.

It's probably an edge case. But what do you think? Is this something that should be improved or more of a "wontfix"?
